# Generated by Django 5.2.3 on 2025-11-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_comment_titel_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='titel',
            name='genre',
            field=models.CharField(choices=[('horors', 'Horors'), ('shooter', 'Shooter'), ('survival', 'Survival'), ('tower defense', 'Tower of Defense'), ('battleground', 'Battleground'), ('mmorpg', 'MMORPG'), ('multiplayer', 'Multiplayer'), ('roleplay', 'Roleplay')], max_length=50, null=True),
        ),
    ]
