# Generated by Django 5.2.3 on 2025-11-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_titel_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('horors', 'Horors'), ('shooter', 'Shooter'), ('survival', 'Survival'), ('tower defense', 'Tower of Defense'), ('battleground', 'Battleground'), ('mmorpg', 'MMORPG'), ('multiplayer', 'Multiplayer'), ('roleplay', 'Roleplay')], max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='titel',
            name='genre',
        ),
        migrations.AddField(
            model_name='titel',
            name='genres',
            field=models.ManyToManyField(blank=True, to='info.genres'),
        ),
    ]
